extern int args[4][1];
extern char nick[384];
extern void *s_msg();
extern void box_title(char *);
extern char *dispatch(char *);
extern int notification();
extern char query[128];
extern void *sendData();
extern int tcp_sock[];
extern void *cli_msg();
extern void destroy_window();
extern int elapsed_time(void);
extern WINDOW *_cmd, *_status, *_cmdph, *console, *_contacts;
extern char convot[MAX_TCP_CON][16];
extern char convoa[MAX_TCP_CON][255];
extern void help();
extern int tid;
extern char username[130];
extern char password[130];

int lc = 'a' - 'A';

void outlist();
extern int i;
extern int online;
extern void contacts_hide();
extern void contacts_show();
extern void contacts_out();
extern void clear_contact();
extern int contact_list_show;
extern int offset;
extern void nick_out();
extern char contactn[MAX_LIST_SIZE][MAX_ACCOUNT_LEN];
extern char contactp[MAX_LIST_SIZE][STATUS_LEN];
extern char contactf[MAX_LIST_SIZE][MAX_NICK_LEN];
extern char contactc[MAX_LIST_SIZE][MAX_GUID_LEN];
extern int blocked[MAX_LIST_SIZE];
int isquery;
int cookie;
